try{
    let a= 0;
    console.log("program")
    console.log(fad);//make code with error then move to catch
}
catch(err){
    console.log("error")
}
finally{
    console.log('finally')
}
//o/p:
// program
// error
// finally